services:
  postgres-rag:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=bdd
      - POSTGRES_DB=bdd_vectorial
    #restart: always
  pgadmin-rag:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-rag
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-rag
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=bdd_vectorial
      - DB_POSTGRESDB_USER=bdd
      - DB_POSTGRESDB_PASSWORD=1234
      - N8N_ENCRYPTION_KEY=279e938ac830593a315c6b7defb9b117c03d5d6677f91958120f46b5590dc7fb
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_RESTRICT_FILE_ACCESS_TO=/home/node/rag_docs/
    volumes:
      - ./n8n_data:/home/node/
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - 11434:11434
    #environment:
    #  - OLLAMA_NUM_PARALLEL=1  # <-- This enables embedding endpoints natively
    volumes:
      - ./ollama_data:/root/.ollama
    #command: serve --embeddings
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-pull:
    image: ollama/ollama:latest
    entrypoint: /bin/sh -c "sleep 5 && ollama pull nomic-embed-text && ollama pull llama3.2"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: no
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_SECRET_KEY=1234
      - OLLAMA_BASE_URL=http://ollama:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
